### ISSUE TITLE
When i try to run webserver i get this

### ISSUE THREAD

**Issue by jeroenp1** [skftn/findex-gui#37]
Findex-GUI 0.2.18
 https://github.com/skftn/findex-gui
 CedSys (c) 2014-2017

Traceback (most recent call last):
  File "/root/findex/lib/python3.5/site-packages/findex_gui/main.py", line 208, in web
    run_async()
  File "/root/findex/lib/python3.5/site-packages/findex_gui/main.py", line 201, in run_async
    from findex_gui.web import app
  File "/root/findex/lib/python3.5/site-packages/findex_gui/web.py", line 41, in <module>
    from findex_gui.orm.connect import Database
  File "/root/findex/lib/python3.5/site-packages/findex_gui/orm/connect.py", line 12, in <module>
    from findex_gui.orm.models import BASE
  File "/root/findex/lib/python3.5/site-packages/findex_gui/orm/models.py", line 24, in <module>
    from findex_common.utils import rand_str
ImportError: cannot import name 'rand_str'

**Comment by skftn** [comment]
I have a working version up via Vagrant.

Please follow https://github.com/skftn/findex-gui#installation

No documentation yet. Let me know how it goes.

**Comment by skftn** [comment]
Try Findex-GUI `0.3.0.1` - available through a Vagrant install (https://github.com/skftn/findex-gui#installation).

Really simple installation. What I've tested that works:

- FTP indexing
- Searching
- Browsing

Let me know what you think.
