### ISSUE TITLE
Cannot run findex after install

### ISSUE THREAD

**Issue by nickbouwhuis** [skftn/findex-gui#7]
After following the brief instruction and trying to run Findex-gui, I get the following: 

    (findex)root@machine:~/findex/bin# Traceback (most recent call last):
      File "/root/findex/bin/findex-gui", line 9, in <module>
        load_entry_point('findex-gui==0.0.1', 'console_scripts', 'findex-gui')()
      File "/root/findex/local/lib/python2.7/site-packages/click-6.0-py2.7.egg/click/core.py", line 695, in __call__
        return self.main(*args, **kwargs)
      File "/root/findex/local/lib/python2.7/site-packages/click-6.0-py2.7.egg/click/core.py", line 675, in main
        rv = self.invoke(ctx)
      File "/root/findex/local/lib/python2.7/site-packages/click-6.0-py2.7.egg/click/core.py", line 1039, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/root/findex/local/lib/python2.7/site-packages/click-6.0-py2.7.egg/click/core.py", line 868, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/root/findex/local/lib/python2.7/site-packages/click-6.0-py2.7.egg/click/core.py", line 513, in invoke
        return callback(*args, **kwargs)
      File "/root/findex/local/lib/python2.7/site-packages/findex_gui-0.0.1-py2.7.egg/findex_gui/daemon.py", line 54, in start
        start_as_daemon()
      File "/root/findex/local/lib/python2.7/site-packages/findex_gui-0.0.1-py2.7.egg/findex_gui/daemon.py", line 43, in start_as_daemon
        from findex_gui.__main__ import main
      File "/root/findex/local/lib/python2.7/site-packages/findex_gui-0.0.1-py2.7.egg/findex_gui/__main__.py", line 11, in <module>
        from findex_gui.bin.config import FindexGuiConfig
      File "/root/findex/local/lib/python2.7/site-packages/gevent-1.1rc1-py2.7-linux-x86_64.egg/gevent/builtins.py", line 58, in __import__
        result = _import(*args, **kwargs)
    ImportError: No module named config
    

Am I doing something wrong? Or is this a big?

**Comment by skftn** [comment]
Hello, you seem to be the first one who attempts to install Findex from scratch. Congrats :+1: 

Your error is due to the `findex-gui` package being outdated. If you git clone the repo right now you will get further. Hopefully.

I say hopefully because the current version is not even an alpha and chances are you will run into more problems. For example; you won't be able to add servers to crawl as this functionality is not in the `findex-gui` package yet. Also, there is no documentation yet.

So if you really want to get it to run; re-download. And else; please wait a month or two!

**Comment by nickbouwhuis** [comment]
Thanks for your response! I cloned the repo again, but still no luck. I'll wait :+1:.
